export default [
  { id: 0, 
    intensity: 1,
    question: 'Sentiste algo muy leve? Quizás estabas en reposo?' },
  { id: 1, 
    intensity: 2,
    question: 'Observas oscilando a los objetos colgantes?' },
  { id: 2, 
    intensity: 3,
    question: 'Se siente parecido al paso de un camión pequeño?' },
  { id: 3, 
    intensity: 4,
    question: 'Se sienten perturbaciones en las ventanas o puertas?' },
  { id: 4, 
    intensity: 5,
    question: 'Se han caído objetos?' },
  { id: 5, 
    intensity: 6,
    question: 'Se han movido muebles pesados?' },
  { id: 6, 
    intensity: 7,
    question: 'Es difícil ponerse de pie?' },
  { id: 7, 
    intensity: 8,
    question: 'Los mueves se han movido completamente de lugar?' },
  { id: 8, 
    intensity: 9,
    question: 'Se observan daños importantes en edificios o pánico generalizado?' },
  { id: 9, 
    intensity: 10,
    question: 'Las estructuras sufren daños, con el marco destruido?' },
  { id: 10, 
    intensity: 11,
    question: 'Quedan pocas estructuras de mampostería en pie? Hay puentes destruidos?' },
  { id: 11, 
    intensity: 12,
    question: 'Es imposible mantenerse en pie? Hay objetos saltando por los aires?' }
];
