export const GET_LAST_QUAKE_SUBMISSION_DATE_REQUEST = 'GET_LATEST_QUAKE_SUBMISSION_DATE_REQUEST';
export const LAST_QUAKE_SUBMISSION_DATE_RECEIVED = 'LAST_QUAKE_SUBMISSION_DATE_RECEIVED';

export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const SURVEY_COMPLETED = 'SURVEY_COMPLETED';
