export const GET_LAST_QUAKE_SUBMISSION_DATE_REQUEST = 'GET_LATEST_QUAKE_SUBMISSION_DATE_REQUEST';
export const LAST_QUAKE_SUBMISSION_DATE_RECEIVED = 'LAST_QUAKE_SUBMISSION_DATE_RECEIVED';

export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const SURVEY_COMPLETED = 'SURVEY_COMPLETED';
export const MODALS_START_TRANSITIONING = 'MODALS_START_TRANSITIONING';
export const MODALS_STOP_TRANSITIONING = 'MODALS_STOP_TRANSITIONING';

export const DISMISS_SURVEY_REQUEST = 'DISMISS_SURVEY_REQUEST';
export const SURVEY_DISMISSED = 'SURVEY_DISMISSED';
