export const GET_LAST_QUAKE_SUBMISSION_DATE_REQUEST = 'GET_LATEST_QUAKE_SUBMISSION_DATE_REQUEST';
export const LAST_QUAKE_SUBMISSION_DATE_RECEIVED = 'LAST_QUAKE_SUBMISSION_DATE_RECEIVED';

export const QUESTION_ANSWERED = 'QUESTION_ANSWERED';
export const SURVEY_COMPLETED = 'SURVEY_COMPLETED';
export const MODALS_START_TRANSITIONING = 'MODALS_START_TRANSITIONING';
export const MODALS_STOP_TRANSITIONING = 'MODALS_STOP_TRANSITIONING';
export const REQUEST_QUAKE_REPORT_RESUBMISSION = 'REQUEST_QUAKE_REPORT_RESUBMISSION';

export const SURVEY_DISMISSED = 'SURVEY_DISMISSED';

export const LAST_QUAKE_INTENSITY_STORED = 'LAST_QUAKE_INTENSITY_STORED';

export const USER_LOCATION_REQUEST = 'USER_LOCATION_REQUEST';
export const USER_LOCATION_RECEIVED = 'USER_LOCATION_RECEIVED';
export const USER_LOCATION_ERROR = 'USER_LOCATION_ERROR';

export const DISABLE_SURVEY_BUTTON = 'DISABLE_SURVEY_BUTTON';
export const ENABLE_SURVEY_BUTTON = 'ENABLE_SURVEY_BUTTON';
export const RESET_SURVEY_VALUES = 'RESET_SURVEY_VALUES';

export const FETCH_NEARBY_QUAKES_REQUEST = 'FETCH_NEARBY_QUAKES_REQUEST';
export const NEARBY_QUAKES_RECEIVED = 'NEARBY_QUAKES_RECEIVED';
